# Generated by Django 5.0.1 on 2024-02-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='causa',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='longitud',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='nivel',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='via',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
