# Generated by Django 5.0.1 on 2024-02-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_nivel_incidencia_zona_incidencia_demarcacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='longitud',
            field=models.CharField(max_length=50),
        ),
    ]
