# Generated by Django 5.0.1 on 2024-02-08 22:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_incidencia_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='tiempo_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
