# Generated by Django 5.0.1 on 2024-02-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_incidencia_tiempo_registro_incidencia_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
