# Generated by Django 5.0.1 on 2024-02-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidencia',
            old_name='zona',
            new_name='nivel',
        ),
    ]
